services:
  db:
    image: postgres:16-alpine
    container_name: todo_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    volumes:
      - todo_data:/var/lib/postgresql/data

volumes:
  todo_data:
